title: "Yuanxin (Yolanda) Li"
description: "Data Analyst | Quant Researcher | Risk Modeler"
author: "Yuanxin Li"
theme: jekyll-theme-minimal
email: yl1053@duke.edu
linkedin_username: yuanxin-li-50896b342
show_downloads: false
