title: "Yuanxin (Yolanda) Li"
description: "Data Analyst | Quant Researcher | Risk Modeler"
author: "Yuanxin Li"
theme: jekyll-theme-cayman
email: yl1053@duke.edu
linkedin_username: yuanxin-li-50896b342

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      read_time: true


nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects



